version: '3.3'

services:
  db:
    image: mariadb:10.5.9
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 's3cr3t'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'mydb'
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
    container_name: app_php
    volumes:
      - ./conf/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - .:/var/www/
    depends_on:
      - "db"

  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/
    working_dir: /var/www/
volumes:
  db_data: